### ISSUE TITLE
Dependencies versioning

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#375]
Hi, 

Following the task #179, the glide.yml should have the commit version of the dependencies, doesn't make sense if you want to commit old version if the dependencies are on master and system can't compile.

Does this change? 

Regards

**Comment by rif** [comment]
@eloycoto please elaborate, I don't understand the problem.

**Comment by eloycoto** [comment]
Ok, this is how glide.yml is now: 

```
package: github.com/cgrates/cgrates
import:
- package: github.com/DisposaBoy/JsonConfigReader
- package: github.com/cenkalti/rpc2
- package: github.com/cgrates/fsock
- package: github.com/cgrates/kamevapi
- package: github.com/cgrates/osipsdagram
- package: github.com/cgrates/rpcclient
- package: github.com/cgrates/structmatcher
- package: github.com/fiorix/go-diameter
  subpackages:
  - /diam
  - diam/avp
  - diam/datatype
  - diam/dict
  - diam/sm
- package: github.com/go-sql-driver/mysql
- package: github.com/gorhill/cronexpr
- package: github.com/jinzhu/gorm
- package: github.com/jinzhu/inflection
- package: github.com/kr/pty
- package: github.com/lib/pq
- package: github.com/mediocregopher/radix.v2
  subpackages:
  - /pool
  - redis
- package: github.com/peterh/liner
- package: github.com/ugorji/go
  subpackages:
  - /codec
- package: golang.org/x/net
  subpackages:
  - /websocket
- package: gopkg.in/fsnotify.v1
- package: gopkg.in/mgo.v2
  subpackages:
  - bson
```

In two months, if you change kamevapi and I want to build my freeze version I can't that the dependency is not correct and I can't build my old version. 

As we spoke in the task #179, glide.yml should have the commit version to keep the build robust. As we have in this commit: 

https://github.com/cgrates/cgrates/blob/90791354cf3f1a3aae4a436df93b4219dff853f8/glide.yaml

```
package: github.com/cgrates/cgrates
import:
  - package: github.com/ugorji/go
    ref:     69aba3eabf3ef86516c9643ecb6d3785ca3b8436
  - package: github.com/jinzhu/gorm
    ref:     611e613459953787a01c2afc82835aa0ba01a045
  - package: golang.org/x/net
    ref:     042ba42fa6633b34205efc66ba5719cd3afd8d38
  - package: github.com/DisposaBoy/JsonConfigReader
    ref:     33a99fdf1d5ee1f79b5077e9c06f955ad356d5f4
  - package: github.com/hoisie/redis
    ref:     788f01e396a99c96c8f56338383926f16841ebae
  - package: github.com/go-sql-driver/mysql
    ref:     69e3ed7607d7c139386480824801584c947c67cf
  - package: github.com/gorhill/cronexpr
    ref:     a557574d6c024ed6e36acc8b610f5f211c91568a
  - package: github.com/lib/pq
    ref:     83c4f410d0aed80a0f44bac6a576a7f2435791f3
  - package: github.com/qor/inflection
    ref:     3272df6c21d04180007eb3349844c89a3856bc25
  - package: gopkg.in/mgo.v2
    ref:     4d04138ffef2791c479c0c8bbffc30b34081b8d9
  - package: github.com/kr/pty
    ref:     f7ee69f31298ecbe5d2b349c711e2547a617d398
  - package: gopkg.in/fsnotify.v1
    ref:     7be54206639f256967dd82fa767397ba5f8f48f5
  - package: github.com/peterh/liner
    ref:     b850cf8c6d0ee52309aad09ac610508c6c75e819
  - package: github.com/cgrates/rpcclient
    ref:     f0f378951e30943373953b44b910cc65ba832da3
  - package: github.com/cgrates/osipsdagram
    ref:     3d6beed663452471dec3ca194137a30d379d9e8f
  - package: github.com/cgrates/kamevapi
    ref:     a376b1f937ba959857929fa3e111c0f3243278c0
  - package: github.com/cgrates/fsock
    ref:     7ec136e2798fbfe44f713f5ee5828ce643dec4c2
  - package: github.com/cenkalti/rpc2
    ref:     2d1be381ce47537e9e076b2b76dc70933162e4e9
  - package: github.com/cenkalti/hub
    ref:     57d753b5f4856e77b3cf8ecce78c97215a7d324d
```

Any solution for this?

Regards
