### ISSUE TITLE
v 0.10.2 in Docker: "cgr-loader -flush_stordb" causes cgr-engine process to crash 

### ISSUE THREAD

**Issue by olofheurgren** [cgrates/cgrates#3988]
Hi!

I'm completely new to CGRates and am trying to set it up (v 0.10.2) using docker-compose. 

Executing the following command in the container running the main `cgr-engine` process:

```
cgr-loader -verbose -flush_stordb -path=/data/ -config_path=/etc/cgrates/
```

`cgr-engine` crashes with the following log output:

```
cgrates_1   | panic: runtime error: invalid memory address or nil pointer dereference
cgrates_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x100d99b]
cgrates_1   | 
cgrates_1   | goroutine 62 [running]:
cgrates_1   | github.com/cgrates/cgrates/engine.(*DataManager).CacheDataFromDB(0x0, 0x1720026, 0x4, 0xc000674c00, 0x3, 0x4, 0x1, 0xc00071f5c0, 0x2)
cgrates_1   | 	/home/dan/go/src/github.com/cgrates/cgrates/engine/datamanager.go:199 +0x7b
cgrates_1   | github.com/cgrates/cgrates/engine.(*CacheS).reloadCache(...)
cgrates_1   | 	/home/dan/go/src/github.com/cgrates/cgrates/engine/caches.go:217
cgrates_1   | github.com/cgrates/cgrates/engine.(*CacheS).V1ReloadCache(0xc0008db720, 0xc000189ac0, 0x0, 0x0, 0xc000674c00, 0x3, 0x4, 0xc0002c6b40, 0x7, 0x9, ...)
cgrates_1   | 	/home/dan/go/src/github.com/cgrates/cgrates/engine/caches.go:227 +0xea4
cgrates_1   | github.com/cgrates/cgrates/apier/v1.(*CacheSv1).ReloadCache(0xc00018d2a8, 0xc000189ac0, 0x0, 0x0, 0xc000674c00, 0x3, 0x4, 0xc0002c6b40, 0x7, 0x9, ...)
cgrates_1   | 	/home/dan/go/src/github.com/cgrates/cgrates/apier/v1/caches.go:104 +0x76
cgrates_1   | reflect.Value.call(0xc000690480, 0xc00018d418, 0x13, 0x171fb4a, 0x4, 0xc0001e4f08, 0x3, 0x3, 0xc0000dee01, 0xc00092b4b0, ...)
cgrates_1   | 	/usr/local/go/src/reflect/value.go:460 +0x8ab
cgrates_1   | reflect.Value.Call(0xc000690480, 0xc00018d418, 0x13, 0xc0000def08, 0x3, 0x3, 0xc0007ca000, 0xc0000def80, 0x888667)
cgrates_1   | 	/usr/local/go/src/reflect/value.go:321 +0xb4
cgrates_1   | net/rpc.(*service).call(0xc000674780, 0xc000212000, 0xc00092b498, 0xc00092b4b0, 0xc000462c00, 0xc0008dbec0, 0x15b0d00, 0xc00047c6c0, 0x199, 0x143fce0, ...)
cgrates_1   | 	/usr/local/go/src/net/rpc/server.go:377 +0x17f
cgrates_1   | created by net/rpc.(*Server).ServeCodec
cgrates_1   | 	/usr/local/go/src/net/rpc/server.go:474 +0x42b
cgrates_lab_cgrates_1 exited with code 2
```

Output from the `cgr-loader` command indicates that the crash happens on the step "Reloading cache".

```
2023/05/29 09:42:13 Destinations:
[...]
2023/05/29 09:42:13 DispatcherHosts:
2023/05/29 09:42:13 Timings:
2023/05/29 09:42:13 	*any
2023/05/29 09:42:13 	*asap
2023/05/29 09:42:13 Rebuilding reverse destinations
2023/05/29 09:42:13 Reloading cache
2023/05/29 09:42:13 Could not reload cache: unexpected EOF
```

Any idea what could be going on?

------------

My setup is the following:

**Dockerfile:**

```Dockerfile
FROM debian:11

RUN apt update && \
    apt install -y wget postgresql-client vim && \
    apt clean

COPY cgrates_0.10.2_amd64.deb /
RUN dpkg -i /cgrates_0.10.2_amd64.deb
RUN rm /cgrates_0.10.2_amd64.deb
```

```yaml
version: '3.7'

services:
  cgrates:
    build:
      context: .
    command: cgr-engine
    depends_on:
      - postgres
      - redis
    environment:
      PGPASSWORD: cgrates_pw
    volumes:
      - ./config/cgrates.json:/etc/cgrates/cgrates.json:ro
      - ./data/:/data/

  postgres:
    build:
      context: ./postgres/
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./ssl/postgres.crt:/var/lib/postgresql/server.crt
      - ./ssl/postgres.key:/var/lib/postgresql/server.key
    environment:
      POSTGRES_PASSWORD: qwerty
      CGRATES_PASSWORD: cgrates_pw
    command: -c ssl=on -c ssl_cert_file="/var/lib/postgresql/server.crt" -c ssl_key_file="/var/lib/postgresql/server.key"

  redis:
    image: redis

volumes:
  postgres:
```

The mounted `data` directory contains some CSV files:

```
DestinationRates.csv  Destinations.csv  Rates.csv  RatingPlans.csv  RatingProfiles.csv
```

and the mounted `cgrates.json` looks like this:

```json
{
  "general": {
    "logger": "*stdout"
  },  

  "data_db": {
    "db_type": "*redis",
    "db_host": "redis"
  },  
  "stor_db": {
    "db_type": "*postgres",
    "db_host": "postgres",
    "db_port": 5432,
    "db_password": "cgrates_pw"
  }
}
```
