### ISSUE TITLE
Wrong default cost when credit balance is less than 0

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#98]
Hi, 

In some accounts when the credit is under 0 the cost for *default  runid doesn't work correctly.  Furthermore the cost_details are empty, I'm testing in the last master commit, tariffplans was reloaded. 

If I add credit all works ok. 

Rated cdrs
```
mysql> select * from rated_cdrs where cgrid='d9b5dbfece24a3461fb597cffe98f6757419e285' \G;
*************************** 1. row ***************************
              id: XXXXX
           cgrid: d9b5dbfece24a3461fb597cffe98f6757419e285
           runid: *default
         reqtype: postpaid
       direction: *out
          tenant: foehn
        category: postpaid
         account: test
         subject: test
     destination: 0044XXXXXX
      setup_time: 2015-06-17 13:32:57
             pdd: 0.000000000
     answer_time: 2015-06-17 13:32:57
           usage: 31.000000000
        supplier:
disconnect_cause:
            cost: 0.0000
      extra_info:
      created_at: 2015-06-17 14:33:03
      updated_at: 0000-00-00 00:00:00
      deleted_at: 0000-00-00 00:00:00
*************************** 2. row ***************************
              id: xxxxxxxx
           cgrid: d9b5dbfece24a3461fb597cffe98f6757419e285
           runid: extra1
         reqtype: rated
       direction: *out
          tenant: foehn
        category: postpaid
         account: test
         subject: test
     destination: 0044xxxxxxxxxx
      setup_time: 2015-06-17 13:32:57
             pdd: 0.000000000
     answer_time: 2015-06-17 13:32:57
           usage: 31.000000000
        supplier:
disconnect_cause:
            cost: 0.0048
      extra_info:
      created_at: 2015-06-17 14:33:03
      updated_at: 0000-00-00 00:00:00
      deleted_at: 0000-00-00 00:00:00
2 rows in set (0.00 sec)
```

Cost_details:
```
*************************** 1. row ***************************
         id: xxxxxx
      cgrid: d9b5dbfece24a3461fb597cffe98f6757419e285
      runid: *default
        tor:
  direction:
     tenant:
   category:
    account:
    subject:
destination:
       cost: 0.0000
  timespans: null
cost_source: CDRS
 created_at: 2015-06-17 14:33:03
 updated_at: 0000-00-00 00:00:00
 deleted_at: 0000-00-00 00:00:00
*************************** 2. row ***************************
         id: xxxxx
      cgrid: d9b5dbfece24a3461fb597cffe98f6757419e285
      runid: extra1
        tor:
  direction:
     tenant:
   category:
    account:
    subject:
destination:
       cost: 0.0000
  timespans: null
cost_source: CDRS
 created_at: 2015-06-17 14:33:03
 updated_at: 0000-00-00 00:00:00
 deleted_at: 0000-00-00 00:00:00
2 rows in set (0.00 sec)
```
